export const routes = {
  HOME: '/',
  PROJECTS: '/projects',
  VERIFY: '/:memberId/:key',
  CAMPAIGNS: '/campaigns',
  PROJECTS_DETAIL: '/projects/:id',
  CAMPAIGNS_DETAIL: '/campaigns/:id',
  ME: {
    INFO: '/me/info',
    DETAIL_PROJECT: '/me/projects/:id',
    UPDATE_PROJECT: '/me/projects/update/:id',
    PROJECT: '/me/projects',
    PROJECT_REGISTER: '/me/projects-register',
    CAMPAIGN: '/me/campaigns',
  },
  ADMIN: {
    INFO: '/admin/info',
    DETAIL_PROJECT: '/admin/projects/:id',
    DETAIL_PENDING: '/admin/pending/:id',
    UPDATE_PROJECT: '/admin/projects/update/:id',
    PROJECT: '/admin/projects',
    PROJECT_REGISTER: '/admin/projects-register',
    CAMPAIGN: '/admin/campaigns',
    MANAGER_MEMBER: '/admin/manager/members',
    MANAGER_PROJECT: '/admin/manager/project',
    MANAGER_STATISTIC: '/admin/manager/statistic',
  },
  FAQS: '/faqs',
  DONATE: '/donate',
  ABOUT: '/about',
  USER: '/user/:id',
  SEARCH: '/search',
};
